create table location_details as
select distinct CONTINENT,
COUNTRY,
PROVINCE,
TIME_ZONE,
POPULATION_DENSITY,
POPULATION,
TOTAL_CITIES,
TOTAL_DISTRICTS,
AREA_KM_2_,
LOCATION,
LOCATION_LEVEL,
ISLAND,
LOCATION_ISO_CODE,
LONGITUDE,
LATITUDE
from covid19_indonesia_data